"""Add column slug, author_id to table post

Revision ID: 0c577581545e
Revises: 3faa24feabc3
Create Date: 2024-02-27 14:18:21.974883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c577581545e'
down_revision = '3faa24feabc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('author_id')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
